#
# https://golangci-lint.run/
#

run:
  timeout: 5m
  skip-files:
    # under development
    # - content/books/book_test.go
    # - content/books/lesson_test.go
    # - .*_test\.go

issues:
  max-issues-per-linter: 0
  max-same-issues: 0


linters-settings:

  thelper:
    test:
      begin: false

  cyclop:
    max-complexity: 16

  gomnd:
    ignored-files:
      # kanji hadamitzky numbers
      - content/kanjis/nummer.go

  varnamelen:
    max-distance: 10
    ignore-names:
      - c
      - i
      - j
      - err

  wsl:
    allow-separated-leading-comment: false

  ireturn:
    allow:
      - anon
      - error
      - empty
      - stdlib
      - generic
      - Runner
      # generic interface names
      - ^(E|K|L|T|V)$

  gocritic:
    disabled-checks:
      - appendAssign

  nlreturn:      
    block-size: 10

  revive:
    rules:
    - name: var-naming
      severity: warning
      disabled: false
      arguments:
      - ["ID"] # AllowList
      - [] # DenyList
      - - upperCaseConst: true


linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exportloopref
    - forcetypeassert
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - grouper
    - importas
    - interfacebloat
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tagalign
    - tagliatelle
    - tenv
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam # Reports unused function parameters [fast: false, auto-fix: false]
    - usestdlibvars
    - varnamelen
    - wastedassign

  disable:
    - depguard # no forbidden packages (yet)
    - exhaustruct # we use builders, so some struct elements are initially not filled
    - gochecknoglobals # globals are used in kanji radicals package
    - gochecknoinits # init is used in kanji radicals package
    - godox # Tool for detection of FIXME, TODO and other comment keywords [fast: true, auto-fix: false]
    - gofumpt # gofmt is sufficient
    - gosmopolitan # we use japanese characters in the code
    - paralleltest
    - promlinter # Prometheus not used
    - whitespace # newline at start of function is ok
    - wsl # newline at start of function is ok
    - zerologlint # zerolog is not used
    - testpackage # might be removed, whitebox tests sometimes useful
    - nonamedreturns # might be disabled
    - funlen
    - forbidigo
    - stylecheck
    - wrapcheck
    - goerr113
    - dupl # maybe later, ignores small differences in code

